# Generated by Django 4.1.9 on 2023-10-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kanal ID'),
        ),
    ]
