# Generated by Django 4.1.9 on 2023-10-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_alter_channel_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(db_index=True, default='12312', max_length=20, verbose_name='Kanal ID'),
            preserve_default=False,
        ),
    ]
