# Generated by Django 4.1.9 on 2023-10-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channel_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='link',
            field=models.CharField(default='1', max_length=64, verbose_name='Kanal URL'),
            preserve_default=False,
        ),
    ]
