# Generated by Django 4.1.9 on 2023-11-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_channel_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='link',
        ),
    ]
