# Generated by Django 4.1.9 on 2023-11-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_remove_channel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='link',
            field=models.CharField(default='t.me/kaireke_sultan', help_text="Na'muna: @savolnoma yoki t.me/savolnoma", max_length=100, verbose_name='Havola'),
            preserve_default=False,
        ),
    ]
