# Generated by Django 4.1.9 on 2023-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.CharField(help_text="Na'muna: @savolnoma yoki t.me/savolnoma", max_length=100, null=True, verbose_name='Havola'),
        ),
    ]
