# Generated by Django 4.1.9 on 2023-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_alter_channel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.CharField(default='qwe', help_text="Na'muna: @savolnoma yoki t.me/savolnoma", max_length=100, verbose_name='Havola'),
            preserve_default=False,
        ),
    ]
