# Generated by Django 4.1.9 on 2023-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Ovoz beruvchi ID'),
        ),
    ]
