# Generated by Django 4.1.9 on 2023-10-28 18:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('channels', '0004_alter_channel_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Javob')),
            ],
            options={
                'verbose_name': 'Javob ',
                'verbose_name_plural': 'Javoblar ',
                'default_related_name': 'choices',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, db_index=True, editable=False, max_length=10, null=True, verbose_name='Xabar ID')),
                ('text', ckeditor.fields.RichTextField(max_length=1023, verbose_name='Savol matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('is_sent', models.BooleanField(default=False, editable=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channel', verbose_name='Yuboriladigan kanal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Savol ',
                'verbose_name_plural': 'Savollar ',
                'default_related_name': 'polls',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.choice', verbose_name='Javob')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll', verbose_name='Savol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.voter', verbose_name='Ovoz beruvchi')),
            ],
            options={
                'verbose_name': 'Ovoz ',
                'verbose_name_plural': 'Ovozlar ',
                'default_related_name': 'voting',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll', verbose_name='Savol'),
        ),
    ]
