# Generated by Django 4.1.9 on 2023-12-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pollshots', verbose_name='Rasm'),
        ),
    ]
